apiVersion: v1
kind: Service
metadata:
  name: frontend-deploy-service
  namespace: gitlab-kubernetes-agent:gitlab-agent
  labels:
    app: frontend-deploy
    tier: frontend
spec:
  selector:
    app: frontend-deploy
    tier: frontend
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 80
  type: LoadBalancer
